### ISSUE TITLE
Resource string for IgxSpreadsheet control

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular-i18n#25]
Do we have a plan to add resource string for IgxSpreadsheet control for localization? As same as IgxGrid, I would like to have localized strings for IgxSpreadsheet control.

**Comment by Lipata** [comment]
@igandrews do we plan to do that?

**Comment by igandrews** [comment]
There are no current plans to do that that I am aware of. This sounds like a feature request for spreadsheet and I don't think it would relate to igniteui-angular-i18n unless we are going to change that to have a dependency on all the igniteui-angular-xxx packages.

**Comment by Lipata** [comment]
@igandrews we will move that repo into the igniteui-angular product, so you are right that it should be in each individual repo. However, the way i18n is used in the app should be similar: https://www.infragistics.com/products/ignite-ui-angular/angular/components/localization.html

We have a [task](https://github.com/IgniteUI/igniteui-angular/issues/6602) that we should start at some point, and at the same time will check the new i18n angular functionalities that Angular exposes.

**Comment by Lipata** [comment]
We've moved the current state of igniteui-angular-i18n into the [igniteui-angular](https://github.com/IgniteUI/igniteui-angular) repo. In that case, what @igandrews has previously said is correct - the localization for the IgxSpreadsheet should come from the component.

@ymita if the request is still present you can log it in the [igniteui-angular-charts](https://github.com/IgniteUI/igniteui-angular-charts) repo.
