### ISSUE TITLE
Errors when updated licensed packages using Ignite UI for Angular Schematic.

### ISSUE THREAD

**Issue by cleverdog** [IgniteUI/igniteui-angular-i18n#37]
1. When using an igniteui-angular-i18n.
2. Updating licensed packages using Ignite UI for Angular Schematic.
3. When building an app, the console shows errors.

[![Image from Gyazo](https://i.gyazo.com/00a05329fbbec22ee91dec05f39fc9d6.png)](https://gyazo.com/00a05329fbbec22ee91dec05f39fc9d6)

**Comment by damyanpetev** [comment]
While we consider options to modify the package or the upgrade process, a quick solution can be adding a path mapping (similar to the one described in the [Licensing topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/ignite-ui-licensing.html#how-to-setup-your-environment-to-use-the-private-npm-feed)) in `tsconfig.base.json` (assuming ng 10):
```json
{
  "compilerOptions": {
    //...
    "paths": {
      "igniteui-angular": ["./node_modules/@infragistics/igniteui-angular"]
    }
  }
}
```
That did the trick in my test app and fixed the compilation. It's also pretty safe to add this redirect even if we make changes in the future to resolve this.
