### ISSUE TITLE
How to internationalize the grid?

### ISSUE THREAD

**Issue by eestein** [IgniteUI/igniteui-angular-i18n#52]
## Question  
I was reading https://www.infragistics.com/products/ignite-ui-angular/angular/components/localization.html and I'd like to confirm, before taking this route, this is the way to do it.
Should I really create a variable with all resources of the grid, manually translated, per language? Aren't there no default resources for "common" languages like German, French, Italian, etc? Only Japanese and Korean by downloading the i18n package?

Is this correct or am I missing something?

 * igniteui-angular version: 8.1.0
 * browser: Firefox

**Comment by Lipata** [comment]
@eestein we are currently adding: [German](https://github.com/IgniteUI/igniteui-angular-i18n/pull/46), [French](https://github.com/IgniteUI/igniteui-angular-i18n/pull/51) (thanks to @DanielRose), [Italian, Chinese (Taiwan and PRC)](https://github.com/IgniteUI/igniteui-angular-i18n/pull/45).
